Revert "mm: Resolve excess arguments"
This reverts commit 657dd712b318c721d25de665c4d790898403e33c.

The opposite happens now that we've picked "proc: add seq_put_decimal_ull_width to speed up /proc/pid/smaps"

../fs/proc/task_mmu.c:484:38: error: too few arguments to function call, expected 4, have 3
  484 |         len += num_to_str(&out[len], 20, ino);
      |                ~~~~~~~~~~                   ^
../include/linux/kernel.h:454:12: note: 'num_to_str' declared here
  454 | extern int num_to_str(char *buf, int size,
      |            ^          ~~~~~~~~~~~~~~~~~~~~
  455 |                       unsigned long long num, unsigned int width);
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Yahya Wessam <yahyawessam2002@gmail.com>